### ISSUE TITLE
signinページ表示時のnext-authエラーの解消

### ISSUE THREAD

**Issue by mmrakt** [mmrakt/nextjs-todo-app#1]
prisma clientの初期化エラーが原因だった

**Comment by mmrakt** [comment]
`yarn dev`時に下記エラー発生。

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (webpack-internal:///./node_modules/react/cjs/react.development.js:1476:13)
    at Object.useEffect (webpack-internal:///./node_modules/react/cjs/react.development.js:1519:20)
    at MyApp (webpack-internal:///./src/pages/_app.tsx:30:50)
    at processChild (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/next/dist/server/render.js:751:45)
    at Object.defaultGetInitialProps (/Users/mimuraakito/workspace/nextjs-todo-app/node_modules/next/dist/server/render.js:389:51)
```

以下を試したが解消できず

- prismaクライアントの本番、ローカル分割する前の状態にコミットをロールバック
- ローカルリポジトリ削除、再度clone
- prisma, next-auth, react, react-domのバージョンアップ
- `_app.tsx`のchild componentを全てコメントアウト

**Comment by mmrakt** [comment]
envの環境変数の読み込み不備が原因だった。
